### ISSUE TITLE
Specify schema name for Oracle

### ISSUE THREAD

**Issue by mpcarter** [datafold/data-diff#115]
Trying to test a comparison to an Oracle database, but I cannot figure out how to inform data-diff which schema the table is in. It only seems to support specifying a table name and thus only tables belonging to the user I am logged in as. 

Our DBAs do not let users log in using the owner of our production schemas (for good reason).

**Comment by erezsh** [comment]
Thanks for the information! That should be pretty simple to do.

Do I understand correctly that the information in USER_TAB_COLUMNS is essentially the same as ALL_TAB_COLUMNS  where `SCHEMA_NAME = <user-name>`?

**Comment by mpcarter** [comment]
Yes that is correct.

**Comment by erezsh** [comment]
@mpcarter I created a PR that I believe corrects this issue (#117 ). If you can give it a try and let me know if it works for you, that would help fast-tracking it into the master branch.

For convenience, you can install it with `pip install git+https://github.com/datafold/data-diff.git@refs/pull/117/head`.

**Comment by mpcarter** [comment]
@erezsh Not sure if you prefer comments here or on the PR. I tried it out and it worked in as much as it was able to query the correct table. However, another error occurred. I ran it debug flag and included output below.

```
(datadiffpr117) datadiff $ data-diff $ORA MYSCHEMA.MY_TABLE $SF MY_TABLE -k ID -d
[08:18:52] DEBUG - Injecting ssl_wrap_socket_with_ocsp
[08:18:52] DEBUG - cache directory: C:\Users\mcarter\AppData\Local\Snowflake\Caches
[08:18:52] DEBUG - Failed to import pyarrow. Cannot use pandas fetch API
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
[08:18:53] DEBUG - Starting new HTTP connection (1): ocsp.snowflakecomputing.com:80
[08:18:53] DEBUG - http://ocsp.snowflakecomputing.com:80 "GET /ocsp_response_cache.json HTTP/1.1" 200 181522
[08:18:56] DEBUG - Running SQL (Oracle): SELECT column_name, data_type, 6 as datetime_precision, data_precision as numeric_precision, data_scale as numeric_scale FROM ALL_TAB_COLUMNS WHERE table_name = 'MY_TABLE' AND owner = 'MYSCHEMA'
[08:18:56] DEBUG - Running SQL (Snowflake): SELECT column_name, data_type, datetime_precision, numeric_precision, numeric_scale FROM information_schema.columns WHERE table_name = 'MY_TABLE' AND table_schema = 'MYSCHEMA'
[08:18:59] DEBUG - Running SQL (Oracle): SELECT min(ID), max(ID) FROM MYSCHEMA.MY_TABLE
[08:18:59] DEBUG - Running SQL (Snowflake): SELECT min("ID"), max("ID") FROM "MYSCHEMA"."MY_TABLE"
[08:19:00] INFO - Diffing tables | segments: 32, bisection threshold: 16384. key-range: 1..21922710, size: 21922709
[08:19:00] INFO - . Diffing segment 1/32, key-range: 1..685085, size: 685084
[08:19:00] INFO - . Diffing segment 2/32, key-range: 685085..1370169, size: 685084
[08:19:00] DEBUG - Running SQL (Oracle): SELECT count(*), sum(to_number(substr(standard_hash(concat(to_char(ID, 'FM99999999999999999999999999999999999999')), 'MD5'), 18), 'xxxxxxxxxxxxxxx')) FROM MYSCHEMA.MY_TABLE WHERE (1 <= ID) AND (ID < 685085)
[08:19:00] DEBUG - Running SQL (Snowflake): SELECT count(*), sum(BITAND(md5_number_lower64(concat(cast(cast("ID" as decimal(38, 0)) as string))), 1152921504606846975)) FROM "MYSCHEMA"."MY_TABLE" WHERE (1 <= "ID") AND ("ID" < 685085)
[08:19:00] DEBUG - Running SQL (Oracle): SELECT count(*), sum(to_number(substr(standard_hash(concat(to_char(ID, 'FM99999999999999999999999999999999999999')), 'MD5'), 18), 'xxxxxxxxxxxxxxx')) FROM MYSCHEMA.MY_TABLE WHERE (685085 <= ID) AND (ID < 1370169)
[08:19:00] DEBUG - Running SQL (Snowflake): SELECT count(*), sum(BITAND(md5_number_lower64(concat(cast(cast("ID" as decimal(38, 0)) as string))), 1152921504606846975)) FROM "MYSCHEMA"."MY_TABLE" WHERE (685085 <= "ID") AND ("ID" < 1370169)
[08:19:01] INFO - . Diffing segment 3/32, key-range: 1370169..2055253, size: 685084
Traceback (most recent call last):
  File "c:\users\mcarter\temp\datadiff\datadiffpr117\lib\site-packages\data_diff\databases\oracle.py", line 35, in _query
[08:19:01] DEBUG - Running SQL (Oracle): SELECT count(*), sum(to_number(substr(standard_hash(concat(to_char(ID, 'FM99999999999999999999999999999999999999')), 'MD5'), 18), 'xxxxxxxxxxxxxxx')) FROM MYSCHEMA.MY_TABLE WHERE (1370169 <= ID) AND (ID < 2055253)
    return super()._query(sql_code)
  File "c:\users\mcarter\temp\datadiff\datadiffpr117\lib\site-packages\data_diff\databases\base.py", line 210, in _query
[08:19:01] DEBUG - Running SQL (Snowflake): SELECT count(*), sum(BITAND(md5_number_lower64(concat(cast(cast("ID" as decimal(38, 0)) as string))), 1152921504606846975)) FROM "MYSCHEMA"."MY_TABLE" WHERE (1370169 <= "ID") AND ("ID" < 2055253)
    return r.result()
  File "C:\Users\mcarter\scoop\apps\python\current\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Users\mcarter\scoop\apps\python\current\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\mcarter\scoop\apps\python\current\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mcarter\temp\datadiff\datadiffpr117\lib\site-packages\data_diff\databases\base.py", line 216, in _query_in_worker
    return _query_conn(self.thread_local.conn, sql_code)
  File "c:\users\mcarter\temp\datadiff\datadiffpr117\lib\site-packages\data_diff\databases\base.py", line 52, in _query_conn
    c.execute(sql_code)
cx_Oracle.DatabaseError: ORA-00909: invalid number of arguments
```

I test ran the Oracle sql manually and it appears the error is coming from the `concat()` call. It only has one argument, but it requires 2.
SELECT count(*), sum(to_number(substr(standard_hash(**concat**(to_char(ID, 'FM99999999999999999999999999999999999999')), 'MD5'), 18), 'xxxxxxxxxxxxxxx')) FROM MYSCHEMA.MY_TABLE WHERE (685085 <= ID) AND (ID < 1370169)

**Comment by erezsh** [comment]
@mpcarter I think I fixed it. Can you try again?

**Comment by mpcarter** [comment]
I'll check it out and report back here this afternoon.

> I was not aware that in Oracle concat requires at least 2 arguments

I do want to mention that Oracle concat *only* accepts 2 arguments. Not more.

**Comment by mpcarter** [comment]
I'll check it out and report back here this afternoon.

> I was not aware that in Oracle concat requires at least 2 arguments

I do want to mention that Oracle concat *only* accepts 2 arguments. Not more.

**Comment by erezsh** [comment]
@mpcarter Thanks for point that out! Do you foresee any issue with doing `(col1 || col2 || col3)` instead?

**Comment by mpcarter** [comment]
Yes `(col1 || col2 || col3)` would work and is how I always concatenate strings in Oracle. 

I can confirm that my initial test using Oracle worked this time!

**Comment by erezsh** [comment]
That's great to hear!

I'll close this issue for now, but feel free to continue the discussion here, or create a new issue if you run into anything else.
