### ISSUE TITLE
TypeError: [TableDiffer] Attribute 'bisection_factor' expected value of type int. Instead got '32'

### ISSUE THREAD

**Issue by davesgonechina** [datafold/data-diff#175]
Works without `--bisection-factor` but when I try to use it e.g. `data-diff db1 table1 db2 table2 --stats --bisection-factor=32` I get this error:

```
Traceback (most recent call last):
  File "/Users/dlyons/.pyenv/versions/3.9.4/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/data_diff/__main__.py", line 87, in main
    return _main(**kw)
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/data_diff/__main__.py", line 177, in _main
    differ = TableDiffer(

  File "<string>", line 9, in __init__
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/runtype/dataclass.py", line 227, in __post_init__
    _post_init(self, config=config, should_cast=check_types == 'cast', sampler=sampler)
  File "/Users/dlyons/.pyenv/versions/3.9.4/lib/python3.9/site-packages/runtype/dataclass.py", line 119, in _post_init
    raise TypeError(msg)
TypeError: [TableDiffer] Attribute 'bisection_factor' expected value of type int. Instead got '32'
```

**Comment by erezsh** [comment]
Is it possible that '32' is given as a string?

**Comment by erezsh** [comment]
> Works with --bisection-factor

What works?

Are you using the latest data-diff version? (make sure with `pip install -U data-diff`)

**Comment by davesgonechina** [comment]
Sorry, edited to say "works without --bisection-factor". It looks like the parameter value 32, being a string from the command line, doesn't get cast to an int?

I'm on v0.2.3.

**Comment by erezsh** [comment]
Yes, you're right, I can reproduce it. We'll fix it soon!

**Comment by erezsh** [comment]
Fixed.
