### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by mathewtapilatu** [datafold/data-diff#201]
**Describe the bug**
sorry before this my first time use data-diff and when i want running this i got error like this even though i try to install 
- pip install psycopg2
- 'pip install data-diff[postgresql]'
the result is still same

```
[16:20:46] INFO - [PostgreSQL] Starting a threadpool, size=1.
[16:20:46] INFO - [PostgreSQL] Starting a threadpool, size=1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 39, in _inner
    return f()
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/postgresql.py", line 10, in import_postgresql
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/__main__.py", line 93, in main
    return _main(**kw)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/__main__.py", line 216, in _main
    for op, columns in diff_iter:
  File "/usr/local/lib/python3.9/dist-packages/data_diff/diff_tables.py", line 325, in diff_tables
    table1, table2 = self._threaded_call("with_schema", [table1, table2])
  File "/usr/local/lib/python3.9/dist-packages/data_diff/diff_tables.py", line 504, in _threaded_call
    return list(self._thread_map(methodcaller(func), iterable))
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/diff_tables.py", line 124, in with_schema
    schema = self.database.query_table_schema(self.table_path, self._relevant_columns)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 183, in query_table_schema
    rows = self.query(self.select_table_schema(path), list)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 100, in query
    res = self._query(sql_code)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 280, in _query
    return r.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 285, in _query_in_worker
    raise self._init_error
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 274, in set_conn
    self.thread_local.conn = self.create_connection()
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/postgresql.py", line 55, in create_connection
    pg = import_postgresql()
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 44, in _inner
    raise ModuleNotFoundError(f"{e}\n\n{s}\n")
ModuleNotFoundError: No module named 'psycopg2'

You can install it using 'pip install data-diff[postgresql]'.

```
**can you explain what should i do?? thats my toml**
```
[database.pg96]
driver = "postgresql"
user = "xxx"
password = "xxx"
database = "xxx"
host = "xxx"
port = 5432

[database.replicapg96]
driver = "postgresql"
user = "xxx"
password = "xxx"
database = "xxx"
host = "xxx"
port = 5432


[run.default]
update_column = "updated_at"
verbose = true

[run.test_diff]
1.database = "xxx"
1.table = "xxx"
2.database = "xxx"
2.table = "xxx"

```

**Comment by erezsh** [comment]
As the error says -

```
You can install it using 'pip install data-diff[postgresql]'.
```

Did you try this?

**Comment by terribilis** [comment]
if @erezsh suggestion doesn't work, you could also try this pip command. 
`pip install psycopg2-binary`

**Comment by mathewtapilatu** [comment]
@erezsh i have done but still same

**Comment by erezsh** [comment]
@mathewtapilatu Run `python -m pip install data-diff[postgresql]` and try again.

Then run data-diff using `python -m data_diff ...`.

If that still doesn't work, please put here the output you get from running `python -m pip install psycopg2`.

**Comment by mathewtapilatu** [comment]
> python -m pip install data-diff[postgresql]
this the result
```
root@test-datadiff:~# python -m pip install data-diff[postgresql]
Requirement already satisfied: data-diff[postgresql] in /usr/local/lib/python3.9/dist-packages (0.2.4)
Requirement already satisfied: toml<0.11.0,>=0.10.2 in /usr/local/lib/python3.9/dist-packages (from data-diff[postgresql]) (0.10.2)
Requirement already satisfied: click<9.0,>=8.1 in /usr/local/lib/python3.9/dist-packages (from data-diff[postgresql]) (8.1.3)
Requirement already satisfied: runtype<0.3.0,>=0.2.6 in /usr/local/lib/python3.9/dist-packages (from data-diff[postgresql]) (0.2.7)
Requirement already satisfied: rich<11.0.0,>=10.16.2 in /usr/local/lib/python3.9/dist-packages (from data-diff[postgresql]) (10.16.2)
Requirement already satisfied: dsnparse in /usr/local/lib/python3.9/dist-packages (from data-diff[postgresql]) (0.1.15)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.9/dist-packages (from rich<11.0.0,>=10.16.2->data-diff[postgresql]) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.9/dist-packages (from rich<11.0.0,>=10.16.2->data-diff[postgresql]) (2.12.0)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.9/dist-packages (from rich<11.0.0,>=10.16.2->data-diff[postgresql]) (0.4.5)
```
when i run the command `python -m pip install psycopg2`
```
WARNING: Discarding https://files.pythonhosted.org/packages/6a/8d/ee5c330823d527a5cd14c833063f825211d7b5de6e4897f72e250c107d85/psycopg2-2.0.12.tar.gz#sha256=542c187531e756867fb60034c393b6f2beca34eeeb3ce2e0089a2b6fb8be1292 (from https://pypi.org/simple/psycopg2/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-2.0.11.tar.gz (255 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_qththl8/psycopg2_6d31791fa5464cdaa9afebe5b2e2e26c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_qththl8/psycopg2_6d31791fa5464cdaa9afebe5b2e2e26c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p48osjm6
         cwd: /tmp/pip-install-_qththl8/psycopg2_6d31791fa5464cdaa9afebe5b2e2e26c/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_qththl8/psycopg2_6d31791fa5464cdaa9afebe5b2e2e26c/setup.py", line 225
        except Warning, w:
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2d/d7/496da11d7c81971870ddd36800419c4f84e8f6208aac5eabedf9f7748729/psycopg2-2.0.11.tar.gz#sha256=e6b4e0e41df97441eff34e00065376414da6488e0d55848a45cd77551dbae434 (from https://pypi.org/simple/psycopg2/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-2.0.10.tar.gz (255 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_qththl8/psycopg2_48d5292df600464390a42aa7d024b954/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_qththl8/psycopg2_48d5292df600464390a42aa7d024b954/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4mwfpqas
         cwd: /tmp/pip-install-_qththl8/psycopg2_48d5292df600464390a42aa7d024b954/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_qththl8/psycopg2_48d5292df600464390a42aa7d024b954/setup.py", line 50, in <module>
        import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/19/79/35c7596bab4456f3610c12ec542a94d51c6781ced587d1d85127210b879b/psycopg2-2.0.10.tar.gz#sha256=e40cc04b43849085725076ae134bfef9e3b087f6dd7c964aeeb930e2f0bc14ab (from https://pypi.org/simple/psycopg2/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2
ERROR: No matching distribution found for psycopg2
```

**Comment by cfernhout** [comment]
@mathewtapilatu could you try to install `psycopg-binary` like @terribilis suggested?

In order to install the normal `psycopg` you have a couple of prerequisites that can be a bit a PITA to make it work, depending on the machine and OS you are working on.

See for some guidance and difference explained between the two packages here: https://www.psycopg.org/docs/install.html#quick-install

**Comment by mathewtapilatu** [comment]
its works thanks @cfernhout

**Comment by mathewtapilatu** [comment]
but i found some error again 
```
Exception in initializer:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 66, in _worker
    initializer(*initargs)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 274, in set_conn
    self.thread_local.conn = self.create_connection()
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/postgresql.py", line 57, in create_connection
    c = pg.connect(**self._args)
  File "/usr/local/lib/python3.9/dist-packages/psycopg2/__init__.py", line 121, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/psycopg2/extensions.py", line 167, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "schema"
```
thats my toml
```
[database.pg96]
driver = "postgresql"
user = "xxx"
password = "xxx"
database = "xxx"
host = "xxx"
port = 5432
schema = "public"

[database.replicapg96]
driver = "postgresql"
user = "xxx"
password = "xxx"
database = "xxx"
host = "xxx"
port = 5432
schema = "public"

[run.default]
update_column = "updated_at"
verbose = true

[run.test_diff]
1.database = "xxx"
1.table = "xxx"
2.database = "xxx"
2.table = "xxx"

```

**Comment by erezsh** [comment]
@mathewtapilatu Looks like `psycopg2` doesn't support a schema argument. But you can use `options="-c public"`.

See here: https://stackoverflow.com/questions/59298580/how-to-specify-schema-in-psycopg2-connection-method

**Comment by mathewtapilatu** [comment]
> @mathewtapilatu Looks like `psycopg2` doesn't support a schema argument. But you can use `options="-c public"`.
> 
> See here: https://stackoverflow.com/questions/59298580/how-to-specify-schema-in-psycopg2-connection-method

seems like doesn't works,if you see an error message does not exist even though the table exists
```
[07:31:30] INFO - [PostgreSQL] Starting a threadpool, size=1.
[07:31:30] INFO - [PostgreSQL] Starting a threadpool, size=1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/data_diff/diff_tables.py", line 124, in with_schema
    schema = self.database.query_table_schema(self.table_path, self._relevant_columns)
  File "/usr/local/lib/python3.9/dist-packages/data_diff/databases/base.py", line 185, in query_table_schema
    raise RuntimeError(f"{self.name}: Table '{'.'.join(path)}' does not exist, or has no columns")
RuntimeError: PostgreSQL: Table 'igate_history' does not exist, or has no columns

```

**Comment by erezsh** [comment]
@mathewtapilatu This looks like the problem is with either `psycopg2` or your postgres config. I recommend that you use "public.igate_history" to avoid this issue.

Can you get it work if you're using `psycopg2` directly?

**Comment by mathewtapilatu** [comment]
> @mathewtapilatu This looks like the problem is with either `psycopg2` or your postgres config. I recommend that you use "public.igate_history" to avoid this issue.
> 
> Can you access the table if you're using `psycopg2` directly?

okay now i can run it, but i don't really understand what this output means? does it mean there is no difference between both table ? @erezsh 
```
root@test-datadiff:~# data-diff --conf test_diff.toml --run test_diff
[03:38:58] INFO - [PostgreSQL] Starting a threadpool, size=1.
[03:38:58] INFO - [PostgreSQL] Starting a threadpool, size=1.
[03:38:58] INFO - Diffing tables | segments: 32, bisection threshold: 16384. key-range: 170628..227967, size: 57339
[03:38:58] INFO - . Diffing segment 1/32, key-range: 170628..172419, size: 1791
[03:38:58] INFO - . Diffing segment 2/32, key-range: 172419..174210, size: 1791
[03:38:58] INFO - . Diffing segment 3/32, key-range: 174210..176001, size: 1791
[03:38:58] INFO - . Diffing segment 4/32, key-range: 176001..177792, size: 1791
[03:38:58] INFO - . Diffing segment 5/32, key-range: 177792..179583, size: 1791
[03:38:58] INFO - . Diffing segment 6/32, key-range: 179583..181374, size: 1791
[03:38:58] INFO - . Diffing segment 7/32, key-range: 181374..183165, size: 1791
[03:38:58] INFO - . Diffing segment 8/32, key-range: 183165..184956, size: 1791
[03:38:58] INFO - . Diffing segment 9/32, key-range: 184956..186747, size: 1791
[03:38:58] INFO - . Diffing segment 10/32, key-range: 186747..188538, size: 1791
[03:38:58] INFO - . Diffing segment 11/32, key-range: 188538..190329, size: 1791
[03:38:58] INFO - . Diffing segment 12/32, key-range: 190329..192120, size: 1791
[03:38:58] INFO - . Diffing segment 13/32, key-range: 192120..193911, size: 1791
[03:38:58] INFO - . Diffing segment 14/32, key-range: 193911..195702, size: 1791
[03:38:58] INFO - . Diffing segment 15/32, key-range: 195702..197493, size: 1791
[03:38:58] INFO - . Diffing segment 16/32, key-range: 197493..199284, size: 1791
[03:38:58] INFO - . Diffing segment 17/32, key-range: 199284..201075, size: 1791
[03:38:58] INFO - . Diffing segment 18/32, key-range: 201075..202866, size: 1791
[03:38:58] INFO - . Diffing segment 19/32, key-range: 202866..204657, size: 1791
[03:38:58] INFO - . Diffing segment 20/32, key-range: 204657..206448, size: 1791
[03:38:58] INFO - . Diffing segment 21/32, key-range: 206448..208239, size: 1791
[03:38:58] INFO - . Diffing segment 22/32, key-range: 208239..210030, size: 1791
[03:38:58] INFO - . Diffing segment 23/32, key-range: 210030..211821, size: 1791
[03:38:58] INFO - . Diffing segment 24/32, key-range: 211821..213612, size: 1791
[03:38:58] INFO - . Diffing segment 25/32, key-range: 213612..215403, size: 1791
[03:38:58] INFO - . Diffing segment 26/32, key-range: 215403..217194, size: 1791
[03:38:58] INFO - . Diffing segment 27/32, key-range: 217194..218985, size: 1791
[03:38:58] INFO - . Diffing segment 28/32, key-range: 218985..220776, size: 1791
[03:38:58] INFO - . Diffing segment 29/32, key-range: 220776..222567, size: 1791
[03:38:58] INFO - . Diffing segment 30/32, key-range: 222567..224358, size: 1791
[03:38:58] INFO - . Diffing segment 31/32, key-range: 224358..226149, size: 1791
[03:38:58] INFO - . Diffing segment 32/32, key-range: 226149..227967, size: 1818
[03:38:58] INFO - Duration: 0.17 seconds.
```

**Comment by erezsh** [comment]
Sorry I replied but looks like it didn't post. Yes, if that's the entire output, it means there is no difference.
