### ISSUE TITLE
Difficulty when trying to use Snowflake (uppercase issues)

### ISSUE THREAD

**Issue by pik94** [datafold/data-diff#305]
**Describe the bug**
Hi, i found a couple of bugs when diffing on for Snowflake tables. 

**Environment to reproduce:**
1. Create test tables:
```
DROP TABLE IF EXISTS ilia_dev.test_table_1;
CREATE TABLE ilia_dev.test_table_1 (
    c1 integer,
    c2 float4,
    c3 text,
    c4 boolean,
    c5 boolean,
    c6 date,
    c7 timestamp,
    c8 timestamp,
    c10 time
);

INSERT INTO ilia_dev.test_table_1(c1,c2,c3,c4,c5,c6,c7,c8,c10)
VALUES
    (1,0.123456789,'A',True,True,'2020-01-01','2020-01-01 00:00:00','2021-12-25 18:47:31','18:47:31'),
    (2,0.01,'ABC',True,True,'2020-01-02','2020-01-02 00:00:00','2021-12-26 18:47:31','18:47:31'),
    (3,0.001,'ABCD',True,True,'2020-01-03','2020-01-03 00:00:00','2021-12-27 18:47:31','18:47:31'),
    (4,0.0001,'ABCDE',False,False,'2020-01-04','2020-01-04 00:00:00','2021-12-28 18:47:31','18:47:31'),
    (5,0.00001,'ABCDEF',False,False,'2020-01-05','2020-01-05 00:00:00','2021-12-29 18:47:31','18:47:31'),
    (null,0.00001,'ABCDEF',False,False,'2020-01-05','2020-01-05 00:00:00','2021-12-30 18:47:31','18:47:31'),
    (8,0.01,'ABCDEF',True,True,'2020-01-05','2020-01-05 00:00:00.123456','2021-12-31 18:47:31.123456','18:47:31.123456'),
    (10,0.01,'ABCDEF',True,True,'2020-01-05','2020-01-05 00:00:00.123456','2022-01-01 18:47:31.123456','18:47:31.123456'),
    (11,0.01,'ABCDEF',True,True,'2020-01-05','2020-01-05 00:00:00.123456','2022-01-02 18:47:31.123456','18:47:31.123456'),
    (12,0.0001,'ABCDE',False,False,'2020-01-04','2020-01-04 00:00:00','2021-12-28 18:47:31','18:47:31'),
    (12,0.0001,'ABCDEF',False,False,'2020-01-04','2020-01-04 00:00:00','2021-12-28 18:47:31','18:47:31');

DROP TABLE IF EXISTS ilia_dev.test_table_2;
CREATE TABLE ilia_dev.test_table_2 (
    c1 integer,
    c3 text,
    c2 float4,
    c5 boolean,
    c6 date,
    c7 text,
    c8 timestamp,
    c9 integer,
    c10 time
);

INSERT INTO ilia_dev.test_table_2(c1,c3,c2,c5,c6,c7,c8,c9,c10)
VALUES
    (1,'AA',0.123456789,True,'2020-01-01','2020-01-01','2021-12-25 18:47:31',1,'18:47:31'),
    (2,'ABC',0.01,True,'2020-01-02','2020-01-02','2021-12-26 18:47:31',2,'18:47:31'),
    (3,'ABBCD',0.001,False,'2020-01-04','2020-01-03','2021-12-27 18:47:31',3,'18:47:31'),
    (4,'ABCDE',0.00015,False,'2020-01-04','2020-01-04','2021-12-28 18:47:31',4,'18:47:31'),
    (4,'ABCDEF',0.00015,False,'2020-01-04','2020-01-04','2021-12-29 18:47:31',4,'18:47:31'),
    (6,'ABCDEF',0.00001,False,'2020-01-05','2020-01-05','2021-12-30 18:47:31',5,'18:47:31'),
    (6,'ABCDEF',0.00001,False,'2020-01-05','2020-01-05','2021-12-31 18:47:31.123456',5,'18:47:31'),
    (null,'ABCDEF',0.00001,False,'2020-01-05','2020-01-05','2022-01-01 18:47:31.123456',5,'18:47:31'),
    (8,'ABCDEF',0.01,False,'2020-01-05','2020-01-05','2022-01-02 18:47:31.123456',99,'18:47:31.123457'),
    (null,null,null,null,null,null,null,null,null),
    (11,'',0.01, False,'2020-01-05','2020-01-05','2022-01-02 18:47:31.123456',99,'18:47:31.123457'),
    (12,'ABCDE',0.00015,False,'2020-01-04','2020-01-04','2021-12-28 18:47:31',4,'18:47:31'),
    (12,'ABCDEF',0.00015,False,'2020-01-04','2020-01-04','2021-12-29 18:47:31',4,'18:47:31');
```
2. Checkout to the latest master [70a7827c](https://github.com/datafold/data-diff/tree/70a7827c4b6028b3617b91e444b0fb0a1d67b3a2): `git checkout 70a7827c`
3. Create virtualenv:
    ```
    python3 -m venv venv
    ```
4. Install `poetry`: `pip install poetry`
5. Install packages: `poetry install`

**The first bug:**

A python script which failed
```
# Optional: Set logging to display the progress of the diff
import logging

from data_diff import connect_to_table, diff_tables


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    columns = ('c2', 'c5', 'c3', 'c6')
    keys = 'c1'

    table1 = connect_to_table(
        "snowflake://<user>:<pass>@<account>/<database>/ILIA_DEV?warehouse=<warehouse>&role=<role>",
        "ILIA_DEV.TEST_TABLE_1",
        key_columns=keys,
        extra_columns=columns,
    )
    table2 = connect_to_table(
        "snowflake://<user>:<pass>@<account>/<database>/ILIA_DEV?warehouse=<warehouse>&role=<role>",
        "ILIA_DEV.TEST_TABLE_2",
        key_columns=keys,
        extra_columns=columns,
    )

    differ = diff_tables(table1, table2)
    for different_row in differ:
        plus_or_minus, columns = different_row
        print(plus_or_minus, columns)
```

Stacktrace with an error:
```
WARNING:database:Mixed Alphanum/Non-Alphanum values detected in column ILIA_DEV.TEST_TABLE_2.C3. It cannot be used as a key.
Traceback (most recent call last):
  File "/home/pik/workspace/data_diff_fork/my_run.py", line 39, in <module>
    for different_row in differ:
  File "/home/pik/workspace/data_diff_fork/data_diff/diff_tables.py", line 153, in _diff_tables_wrapper
    raise error
  File "/home/pik/workspace/data_diff_fork/data_diff/diff_tables.py", line 124, in _diff_tables_wrapper
    self._validate_and_adjust_columns(table1, table2)
  File "/home/pik/workspace/data_diff_fork/data_diff/hashdiff_tables.py", line 75, in _validate_and_adjust_columns
    raise ValueError(f"Column '{c1}' not found in schema for table {table1}")
ValueError: Column 'c1' not found in schema for table TableSegment(database=<data_diff.databases.snowflake.Snowflake object at 0x7f6de64b09d0>, table_path=('ILIA_DEV', 'TEST_TABLE_1'), key_columns=('c1',), update_column=None, extra_columns=('c2', 'c5', 'c3', 'c6'), min_key=None, max_key=None, min_update=None, max_update=None, where=None, case_sensitive=True, _schema={'C1': Decimal(precision=0), 'C5': <data_diff.sqeleton.databases.database_types.Boolean object at 0x7f6de2432d00>, 'C6': UnknownColType(text='DATE'), 'C2': Float(precision=7), 'C3': <data_diff.sqeleton.databases.database_types.String_VaryingAlphanum object at 0x7f6de249c760>})
```

I think the reason is that Snowflake handle columns in upper case so when parsing schema it returns column names in upper case here: https://github.com/datafold/data-diff/blob/master/data_diff/sqeleton/databases/base.py#L299-L320

**The second bug:**

A python script which failed
```
# Optional: Set logging to display the progress of the diff
import logging

from data_diff import connect_to_table, diff_tables


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    columns = ('c2', 'c5', 'c3', 'c6')
    keys = 'c1'

    table1 = connect_to_table(
        "snowflake://<user>:<pass>@<account>/<database>/ILIA_DEV?warehouse=<warehouse>&role=<role>",
        "ilia_dev.test_table_1",
        key_columns=keys,
        extra_columns=columns,
    )
    table2 = connect_to_table(
        "snowflake://<user>:<pass>@<account>/<database>/ILIA_DEV?warehouse=<warehouse>&role=<role>",
        "ilia_dev.test_table_2",
        key_columns=keys,
        extra_columns=columns,
    )

    differ = diff_tables(table1, table2)
    for different_row in differ:
        plus_or_minus, columns = different_row
        print(plus_or_minus, columns)
```

Stacktrace:
```
Traceback (most recent call last):
  File "/home/pik/workspace/data_diff_fork/my_run.py", line 41, in <module>
    for different_row in differ:
  File "/home/pik/workspace/data_diff_fork/data_diff/diff_tables.py", line 153, in _diff_tables_wrapper
    raise error
  File "/home/pik/workspace/data_diff_fork/data_diff/diff_tables.py", line 123, in _diff_tables_wrapper
    table1, table2 = self._threaded_call("with_schema", [table1, table2])
  File "/home/pik/workspace/data_diff_fork/data_diff/diff_tables.py", line 56, in _threaded_call
    return list(self._thread_map(methodcaller(func), iterable))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pik/workspace/data_diff_fork/data_diff/table_segment.py", line 78, in with_schema
    return self._with_raw_schema(self.database.query_table_schema(self.table_path))
  File "/home/pik/workspace/data_diff_fork/data_diff/sqeleton/databases/base.py", line 308, in query_table_schema
    raise RuntimeError(f"{self.name}: Table '{'.'.join(path)}' does not exist, or has no columns")
RuntimeError: Snowflake: Table 'ilia_dev.test_table_1' does not exist, or has no columns

Process finished with exit code 1

```

_The possible reason_
Again, the problem is that Snowflake does uppercase. The Snowflake information schema stores column names, table names etc in upper case so schema [fetching](https://github.com/datafold/data-diff/blob/master/data_diff/sqeleton/databases/base.py#L299-L320) fails if the user input in lower case:
```
SELECT column_name, data_type, datetime_precision, numeric_precision, numeric_scale FROM information_schema.columns WHERE table_name = 'test_table_1' AND table_schema = 'ilia_dev'
```

**Describe the environment**

OS: Ubuntu 20.04.5 LTS
Python version:  3.8.10
Data diff version: the latest master [70a7827c](https://github.com/datafold/data-diff/tree/70a7827c4b6028b3617b91e444b0fb0a1d67b3a2)

**Comment by erezsh** [comment]
Hi @pik94 , thanks for the detailed report.

Please try to avoid using titles like "X does not work" when the problem is only a specific use or sub-feature of X.

As for the report - 

- Error 1 - I don't see a problem here. You gave the wrong column name, so it throws an error. Maybe we can give a better error, but other than that, what's the problem?
- Error 2- Same thing, the table is in uppercase in the database, but you wrote it in lower-case. So what should we do, other than throw an error?

**Comment by pik94** [comment]
Hi @erezsh , thank you for your reply.

> Error 1

Regarding the first bug you said that i provided wrong column names. What do you mean? `c1` is in both tables, and i use it as a primary key for diffing. Should i use a upper-case column `C1` as input?

 > Error 2

Oh, sorry, my bad. I attached a wrong input (edited ir) in the second script. I used lower-case table names there.

**Comment by erezsh** [comment]
>  Should i use a upper-case column C1 as an input?

That is the name of the column, then yes. Or, you can set `TableSegment.case_sensitive` to False

> I used lower-case table names there.

So, same answer. You're using the wrong name, so of course you get an error.
