### ISSUE TITLE
Error comparing table with FreeMarker templates

### ISSUE THREAD

**Issue by proteus-russ** [datafold/data-diff#398]
Comparing a single column in two tables that contains FreeMarker templates and an error is logged.  I'm not sure if the diff is stopped due to this error.

command:
```
data-diff postgresql://localhost/database table table_before_change --assume-unique-key -j 6 -k id -c subject
```

```
[14:46:30] ERROR - closing tag '[/#if]' at position 6430 doesn't match any open tag
Exception ignored in: <generator object TableDiffer._diff_tables_wrapper at 0x105b1d3f0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/data_diff/diff_tables.py", line 230, in _diff_tables_wrapper
    info_tree.aggregate_info()
  File "/usr/local/lib/python3.10/site-packages/data_diff/info_tree.py", line 52, in aggregate_info
    self.info.update_from_children(c.info for c in self.children)
  File "/usr/local/lib/python3.10/site-packages/data_diff/info_tree.py", line 34, in update_from_children
    2: sum(c.rowcounts[2] for c in child_infos if c.rowcounts),
  File "/usr/local/lib/python3.10/site-packages/data_diff/info_tree.py", line 34, in <genexpr>
    2: sum(c.rowcounts[2] for c in child_infos if c.rowcounts),
KeyError: 2
```

With debug enabled (snipped out only the exception from the debug log)
```
    rich_text = render_markup(
  File "/usr/local/lib/python3.10/site-packages/rich/markup.py", line 161, in render
[15:00:07] DEBUG - Querying for different rows
[15:00:07] DEBUG - Running SQL (PostgreSQL): SELECT count(*) AS "count" FROM "table" WHERE ("id" >= 2546) AND ("id" < 2656)
[15:00:07] DEBUG - Collecting stats for table #1
[15:00:07] DEBUG - Collecting stats for table #2
[15:00:07] DEBUG - Testing for null keys
[15:00:07] DEBUG - Running SQL (PostgreSQL): SELECT count(*) AS "count" FROM "table_before_change" WHERE ("id" >= 2546) AND ("id" < 2656)
    raise MarkupError(
[15:00:07] DEBUG - Counting exclusive rows
rich.errors.MarkupError: closing tag '[/#if]' at position 6430 doesn't match any open tag
```

```
data-diff --version
v0.4.1
```

This is on an Intel Mac running macOS Ventura 13.1 (22C65)

**Comment by proteus-russ** [comment]
I ended up doing a sorted dump of the id and freemarker column data and doing a diff with the diff tool on macOS 13.1. I received many more results, so I think that error stopped processing or there is another bug.

**Comment by erezsh** [comment]
Can you please run datadiff with the `-d` flag  (or `--debug`), and post the entire output?

**Comment by proteus-russ** [comment]
I'm sorry I cannot provide the entire output as it includes client data that I cannot disclose.
