### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by tranhoangnguyen03** [datafold/data-diff#57]
I'm running data-diff on Linux os, specifically via Google Colab.

Here's my command which is constructed following the example on in your **Example Command and Output** section:

`python -m data_diff "snowflake://$USER_1:$PASSWORD_1@$SNOWFLAKE_ACCOUNT/$DATAWAREHOUSE?database=$DATABASE&schema=$SCHEMA1" "same_table" "snowflake://$USER_2:$PASSWORD_2@$SNOWFLAKE_ACCOUNT/$DATAWAREHOUSE?database=$DATABASE&schema=$SCHEMA2" "same_table"`

Here's the error message. Please help, I'm trying to setup a Workflow on GitAction, but I run into problem at this very first step.
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 159, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 132, in main
    diff_iter = differ.diff_tables(table1, table2)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 208, in diff_tables
    end_key = max(maxs) + 1
TypeError: can only concatenate str (not "int") to str
```

**Comment by sirupsen** [comment]
The latest master has also been released as 0.0.5

**Comment by tranhoangnguyen03** [comment]
Hi Erezsh,

I upgraded to 0.0.5, and the above command gave the following error message:
`ValueError: Must provide warehouse. Expected format: 'snowflake://<user>:<pass>@<account>/<database>/<schema>?warehouse=<warehouse>'`

I modify the command according to the expected format, and received this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 164, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 137, in main
    diff_iter = differ.diff_tables(table1, table2)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 238, in diff_tables
    key_ranges = self._threaded_call("query_key_range", [table1, table2])
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 319, in _threaded_call
    return list(self._thread_map(methodcaller(func), iter))
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 167, in query_key_range
    min_key, max_key = self.database.query(select, tuple)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/database.py", line 88, in query
    res = self._query(sql_code)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/database.py", line 364, in _query
    return _query_conn(self._conn, sql_code)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/database.py", line 65, in _query_conn
    c.execute(sql_code)
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/cursor.py", line 799, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/errors.py", line 277, in errorhandler_wrapper
    error_value,
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/errors.py", line 214, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 002003 (42S02): SQL compilation error:
Object '"stg_facebook_adsets"' does not exist or not authorized.
```
I can guarantee that `stg_facebook_adsets` exists in both schemas I'm reading from.

**Comment by erezsh** [comment]
This error usually happens when the schema is incorrect. Make sure to provide the schema in uppercase, if it's uppercase in the database.

**Comment by sirupsen** [comment]
@tranhoangnguyen03 did it work when you upper-cased the schema?

**Comment by tranhoangnguyen03** [comment]
I upper-cased and got the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 164, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 137, in main
    diff_iter = differ.diff_tables(table1, table2)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 238, in diff_tables
    key_ranges = self._threaded_call("query_key_range", [table1, table2])
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 319, in _threaded_call
    return list(self._thread_map(methodcaller(func), iter))
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 167, in query_key_range
    min_key, max_key = self.database.query(select, tuple)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/database.py", line 88, in query
    res = self._query(sql_code)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/database.py", line 364, in _query
    return _query_conn(self._conn, sql_code)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/database.py", line 65, in _query_conn
    c.execute(sql_code)
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/cursor.py", line 799, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/errors.py", line 277, in errorhandler_wrapper
    error_value,
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/usr/local/lib/python3.7/dist-packages/snowflake/connector/errors.py", line 214, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 000904 (42000): SQL compilation error: error line 1 at position 11
invalid identifier '"id"'
```

**Comment by erezsh** [comment]
It looks like the "id" column is also upper case. Added `-k ID` might help.

**Comment by tranhoangnguyen03** [comment]
with `-k ID`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 164, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/__main__.py", line 137, in main
    diff_iter = differ.diff_tables(table1, table2)
  File "/usr/local/lib/python3.7/dist-packages/data_diff/diff_tables.py", line 242, in diff_tables
    min_key = min(map(int, mins))
ValueError: invalid literal for int() with base 10: '000007fa4ea55f4d0c799d5ea4b714ca'
```

**Comment by erezsh** [comment]
Yes, we currently don't support hex ids. Sorry! It's on our TODO list, hopefully we'll get to it soon.

**Comment by sirupsen** [comment]
Yep—closing as it's now a dup of https://github.com/datafold/data-diff/issues/59 — thanks for bearing with us!
