### ISSUE TITLE
BigQuery help URI

### ISSUE THREAD

**Issue by kning** [datafold/data-diff#60]
I know it's not fully tested yet, but it'd be nice to know what the URI format should look like for a BigQuery dataset on the README.

**Comment by erezsh** [comment]
The format is `bigquery://<project>/<dataset>`.

I'll update it in the README too.

**Comment by kning** [comment]
how does data diff authenticate with my bigquery project though? here's what i'm trying locally btw and the error I'm getting (just pulled latest):
```
➜  data-diff git:(master) poetry run python3 -m data_diff bigquery://bigquery-public-data/austin_311 311_service_requests bigquery://bigquery-public-data/austin_311 311_service_r
equests
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kennethning/code/data-diff/data_diff/__main__.py", line 164, in <module>
    main()
  File "/Users/kennethning/Library/Caches/pypoetry/virtualenvs/data-diff-L79wyqPg-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kennethning/Library/Caches/pypoetry/virtualenvs/data-diff-L79wyqPg-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/kennethning/Library/Caches/pypoetry/virtualenvs/data-diff-L79wyqPg-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kennethning/Library/Caches/pypoetry/virtualenvs/data-diff-L79wyqPg-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kennethning/code/data-diff/data_diff/__main__.py", line 109, in main
    db1 = connect_to_uri(db1_uri, threads)
  File "/Users/kennethning/code/data-diff/data_diff/database.py", line 427, in connect_to_uri
    return BigQuery(dsn.host, path)
  File "/Users/kennethning/code/data-diff/data_diff/database.py", line 299, in __init__
    from google.cloud import bigquery
ModuleNotFoundError: No module named 'google.cloud'
```

**Comment by erezsh** [comment]
See this: https://github.com/googleapis/python-bigquery#quick-start

If you have to go through all the steps. Once the environment is set up, make sure you can run this example: https://github.com/googleapis/python-bigquery#perform-a-query

Then you can use data-diff.

**Comment by kning** [comment]
thanks for the guidance, looks like it's working now. it looks like i still actually had to qualify my table name with the dataset name for some reason, which was somewhat unexpected.

```
data_diff.database.ConnectError: Exception when trying to execute SQL code:
    SELECT min(`id`), max(`id`) FROM `my_first_dbt_model`

Got error: 400 Table "my_first_dbt_model" must be qualified with a dataset (e.g. dataset.table).

Location: US
Job ID: bc3b8b9a-d667-46f2-bf2b-5d81282c2a47

(env) ➜  bigquery data-diff bigquery://dbt-tutorial-314920/dbt_kenny dbt_kenny.my_first_dbt_model bigquery://dbt-tutorial-314920/dbt_kenny dbt_kenny.my_second_dbt_model
(env) ➜  bigquery data-diff bigquery://dbt-tutorial-314920/dbt_kenny dbt_kenny.my_first_dbt_model bigquery://dbt-tutorial-314920/dbt_kenny dbt_kenny.my_second_dbt_model --verbose

[18:02:39] INFO - Diffing tables | segments: 32, bisection threshold: 16384. key-range: 1..2, size: 1
[18:02:40] INFO - Diff found 0 different rows.
[18:02:40] INFO - Duration: 2.49 seconds.
```

**Comment by erezsh** [comment]
Sorry, we're still working out the kinks! We'll sort it out soon.

Glad to hear it's working now!

**Comment by sirupsen** [comment]
@kning out of curiosity, what's your use-case of diffing BigQuery -> BigQuery? 👂🏻

**Comment by kning** [comment]
yup, i'm actually working on a blogpost with datafold and just testing out the open source tool a bit. might have some more questions in the future :)

**Comment by kning** [comment]
also a random note on the set up: it'd be nice to have the bq setup steps included in the readme as a pre-req before using data-diff with bigquery and/or somehow abstract away it entirely like how dbt does it. with dbt, you just need to point your profiles yml to a local service account keyfile and you're good to go, no need to install anything additional.

**Comment by sirupsen** [comment]
Yeah, BQ is good for that with the key files indeed.. Our focus right now is stability, making sure it works for more types, and better errors. Ergonomics are definitely required... We know it's painful to get it to run the first time. Assembling one production URI is enough trouble, two is even worse :(
