### ISSUE TITLE
TypeError when running for MySQL

### ISSUE THREAD

**Issue by dschultz5197** [datafold/data-diff#603]
**Describe the bug**
Attempting to run data-diff for a MySQL table is resulting in `TypeError: [UnknownColType] Attribute 'text' expected value of type str. Instead got b'int'`

Below is output running the CLI.

```
~/code/test $ data-diff mysql://user:password@mysql_host:3306/database table_a table_b --key-columns=col_a --columns=col_b --debug
[14:03:57] INFO - Parsing DSN mysql://user:password@mysql_host:3306/database with ConnectionURI
[14:03:57] DEBUG - Parsed scheme mysql
[14:03:57] DEBUG - Parsed authority with 65 characters
[14:03:57] DEBUG - Parsed username user
[14:03:57] DEBUG - Parsed password with 6 characters
[14:03:57] DEBUG - Parsed host mysql_host with port 3306
[14:03:57] DEBUG - Parsed path /database
[14:03:57] DEBUG - Parsed query with 0 characters
[14:03:57] DEBUG - Parsed query_params with  keys
[14:03:57] INFO - [MySQL] Starting a threadpool, size=1.
[14:03:57] DEBUG - Running SQL (MySQL): SET @@session.time_zone='+00:00'
[14:03:57] DEBUG - # _do_auth(): user: user
[14:03:57] DEBUG - # _do_auth(): self._auth_plugin:
[14:03:57] DEBUG - # _do_auth(): user: user
[14:03:57] DEBUG - # _do_auth(): password: password
[14:03:57] DEBUG - new_auth_plugin: mysql_native_password
[14:03:57] DEBUG - Running SQL (MySQL): SELECT column_name, data_type, datetime_precision, numeric_precision, numeric_scale FROM information_schema.columns WHERE table_name = 'table_a' AND table_schema = 'database'
[14:03:57] DEBUG - Running SQL (MySQL): SELECT column_name, data_type, datetime_precision, numeric_precision, numeric_scale FROM information_schema.columns WHERE table_name = 'table_b' AND table_schema = 'database'
[14:03:57] DEBUG - [MySQL] Schema = {'col_a': ('col_a', b'enum', None, None, None), 'col_b': ('col_b', b'datetime', 0, None, None), 'col_c': ('col_c', b'varchar', None, None, None), 'col_d': ('col_d', b'varchar', None, None, None), 'col_e': ('col_e', b'enum', None, None, None), 'col_f': ('col_f', b'datetime', 0, None, None), 'col_g': ('col_g', b'varchar', None, None, None), 'col_h': ('col_h', b'tinyint', None, 3, 0), 'col_i': ('col_i', b'varchar', None, None, None)}
[14:03:57] DEBUG - [MySQL] Schema = {'col_a': ('col_a', b'enum', None, None, None), 'col_b': ('col_b', b'datetime', 0, None, None), 'col_c': ('col_c', b'varchar', None, None, None), 'col_d': ('col_d', b'varchar', None, None, None), 'col_e': ('col_e', b'enum', None, None, None), 'col_f': ('col_f', b'datetime', 0, None, None), 'col_g': ('col_g', b'varchar', None, None, None), 'col_h': ('col_h', b'tinyint', None, 3, 0), 'col_i': ('col_i', b'varchar', None, None, None)}
[14:03:57] DEBUG - Available mutual columns: {'col_b', 'col_e', 'col_a', 'col_i', 'col_d', 'col_f', 'col_h', 'col_c', 'col_g'}
[14:03:57] INFO - Diffing schemas...
[14:03:57] INFO - Diffing using columns: key=('col_a',) update=None extra=('col_b',).
[14:03:57] INFO - Using algorithm 'joindiff'.
[14:03:57] ERROR - [UnknownColType] Attribute 'text' expected value of type str. Instead got b'int'
Traceback (most recent call last):
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/runtype/dataclass.py", line 112, in _post_init
    config.ensure_isa(value, field.type, sampler)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/runtype/validation.py", line 16, in ensure_isa
    t.validate_instance(obj, sampler)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/runtype/pytypes.py", line 100, in validate_instance
    raise TypeMismatchError(obj, self)
runtype.base_types.TypeMismatchError: (b'int', str)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<user>/code/test/venv/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/data_diff/__main__.py", line 277, in main
    return _data_diff(**kw)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/data_diff/__main__.py", line 450, in _data_diff
    segments = [
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/data_diff/__main__.py", line 451, in <listcomp>
    TableSegment(db, table_path, key_columns, update_column, columns, **options)._with_raw_schema(raw_schema)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/data_diff/table_segment.py", line 141, in _with_raw_schema
    schema = self.database._process_table_schema(self.table_path, raw_schema, self.relevant_columns, self._where())
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/data_diff/sqeleton/databases/base.py", line 446, in _process_table_schema
    col_dict = {row[0]: self.dialect.parse_type(path, *row) for _name, row in filtered_schema.items()}
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/data_diff/sqeleton/databases/base.py", line 446, in <dictcomp>
    col_dict = {row[0]: self.dialect.parse_type(path, *row) for _name, row in filtered_schema.items()}
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/data_diff/sqeleton/databases/base.py", line 238, in parse_type
    return UnknownColType(type_repr)
  File "<string>", line 4, in __init__
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/runtype/dataclass.py", line 227, in __post_init__
    _post_init(self, config=config, should_cast=check_types == 'cast', sampler=sampler)
  File "/Users/<user>/code/test/venv/lib/python3.9/site-packages/runtype/dataclass.py", line 119, in _post_init
    raise TypeError(msg)
TypeError: [UnknownColType] Attribute 'text' expected value of type str. Instead got b'int'
```
**Describe the environment**
Python 3.9.16
mysql 8.0.26-16
data-diff==0.7.8
mysql-connector-python==8.0.29

Additionally, I received the same error using the Python API, and on Python 3.10.9 (both with CLI and Python API).
This was run on Mac with the Apple M1 Pro Chip running macOS Monterey.

**Comment by dlawin** [comment]
Thanks for reporting this @dschultz5197

**Comment by cbuckle1** [comment]
Any update on this issue?

**Comment by leoebfolsom** [comment]
@cbuckle1 inquiring on the capacity of our team to address it, and if so, by when; please stand by. Thank you for your patience.

**Comment by dschultz5197** [comment]
I attempted on the latest version, and now receive a NotImplementedError

```
Traceback (most recent call last):
  File "/Users/danielschultz/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/danielschultz/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/danielschultz/.vscode/extensions/ms-python.python-2024.0.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/danielschultz/.vscode/extensions/ms-python.python-2024.0.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/danielschultz/.vscode/extensions/ms-python.python-2024.0.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/danielschultz/.vscode/extensions/ms-python.python-2024.0.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/danielschultz/.vscode/extensions/ms-python.python-2024.0.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/danielschultz/.vscode/extensions/ms-python.python-2024.0.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/danielschultz/code/airflow-python-environments/data-diff/scripts/run-data-diff.py", line 123, in <module>
    run_data_diff(
  File "/Users/danielschultz/code/airflow-python-environments/data-diff/scripts/run-data-diff.py", line 115, in run_data_diff
    for diff in table_diff:
  File "/Users/danielschultz/code/airflow-python-environments/data-diff/data-diff/lib/python3.10/site-packages/data_diff/diff_tables.py", line 95, in __iter__
    for i in self.diff:
  File "/Users/danielschultz/code/airflow-python-environments/data-diff/data-diff/lib/python3.10/site-packages/data_diff/diff_tables.py", line 266, in _diff_tables_wrapper
    raise error
  File "/Users/danielschultz/code/airflow-python-environments/data-diff/data-diff/lib/python3.10/site-packages/data_diff/diff_tables.py", line 239, in _diff_tables_wrapper
    yield from self._diff_tables_root(table1, table2, info_tree)
  File "/Users/danielschultz/code/airflow-python-environments/data-diff/data-diff/lib/python3.10/site-packages/data_diff/diff_tables.py", line 274, in _diff_tables_root
    return self._bisect_and_diff_tables(table1, table2, info_tree)
  File "/Users/danielschultz/code/airflow-python-environments/data-diff/data-diff/lib/python3.10/site-packages/data_diff/diff_tables.py", line 299, in _bisect_and_diff_tables
    raise NotImplementedError(f"Cannot use a column of type {kt} as a key")
NotImplementedError: Cannot use a column of type UnknownColType(_notes=[], text=b'int') as a key
```
