### ISSUE TITLE
Breaks on dsnparse >= 0.2.0

### ISSUE THREAD

**Issue by dmorel** [datafold/data-diff#616]
This happens on python 3.9.7 and 3.10.10 (so basically anything > 3.8 I guess); same behaviour on github action (ubuntu-latest)  and mac M1, with the same versions.

```text
❯ data-diff --debug 'postgresql://dbuser:********@localhost:2000/mydb?sslmode=require' 'public.foo' 'snowflake://DBUSER:************@************.eu-central-1/mydb/myschema?warehouse=MY_WH' 'FOO' -k 'id' -c 'created_at' -c 'updated_at' --json --stats
[21:07:51] INFO - Parsing DSN postgresql://airbyte:****************@localhost:2000/*******?sslmode=require with ConnectionURI
[21:07:51] DEBUG - Parsed scheme postgresql
[21:07:51] DEBUG - Parsed authority with 43 characters
[21:07:51] DEBUG - Parsed username dbuser
[21:07:51] DEBUG - Parsed password with 20 characters
[21:07:51] DEBUG - Parsed host localhost with port 2000
[21:07:51] DEBUG - Parsed path /mydb
[21:07:51] DEBUG - Parsed query with 15 characters
[21:07:51] DEBUG - Parsed query_params with sslmode keys
[21:07:51] ERROR - dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/data_diff/__main__.py", line 277, in main
    return _data_diff(**kw)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/data_diff/__main__.py", line 355, in _data_diff
    db1 = connect(database1, threads1 or threads)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/data_diff/sqeleton/databases/_connect.py", line 266, in __call__
    conn = self.connect_to_uri(db_conf, thread_count)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/data_diff/sqeleton/databases/_connect.py", line 173, in connect_to_uri
    kw = matcher.match_path(dsn)
  File "/Users/dmorel/Library/Caches/pypoetry/virtualenvs/myrepo-_6EoNtbL-py3.9/lib/python3.9/site-packages/data_diff/sqeleton/databases/_connect.py", line 35, in match_path
    dsn_dict = dict(dsn.query)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by dmorel** [comment]
And now I can't make it work anymore even going back to 3.8, this is driving me nuts. Must dig further.

**Comment by dmorel** [comment]
Mystery solved: not a python version issue, but dsnparse issue: 0.1.15 works, 0.2.0 is broken (not splitting on the = sign)

**Comment by dlawin** [comment]
> Mystery solved: not a python version issue, but dsnparse issue: 0.1.15 works, 0.2.0 is broken (not splitting on the = sign) This is because dsnparse's return changed in version 0.2.0 for "query":
> 
> * 0.1.15: r.query_str = "param1=value", r.query = {"param1": "value"}
> * 0.2.0: r.query = "param1=value", r.query_params = {"param1": "value"}
>   So it looks like a good idea to lock the version for this dependency.

Hmm yep it looks like the structure of a dsnparse.ParseResult has changed:
```
0.1.15

╭───────────────────── <class 'dsnparse.ParseResult'> ──────────────────────╮
│ hold the results of a parsed dsn                                          │
│                                                                           │
│ ╭───────────────────────────────────────────────────────────────────────╮ │
│ │ <dsnparse.ParseResult object at 0x1050ae430>                          │ │
│ ╰───────────────────────────────────────────────────────────────────────╯ │
│                                                                           │
│    anchor = ''                                                            │
│  database = 'postgres'                                                    │
│    dbname = 'postgres'                                                    │
│       dsn = 'postgresql://postgres:Password1@localhost/postgres?test=123' │
│  fragment = ''                                                            │
│      host = 'localhost'                                                   │
│   hostloc = 'localhost'                                                   │
│  hostname = 'localhost'                                                   │
│    netloc = 'postgres:Password1@localhost'                                │
│    params = ''                                                            │
│  password = 'Password1'                                                   │
│      path = '/postgres'                                                   │
│     paths = ['postgres']                                                  │
│      port = None                                                          │
│     query = {'test': '123'}                                               │
│ query_str = 'test=123'                                                    │
│    scheme = 'postgresql'                                                  │
│   schemes = ['postgresql']                                                │
│    secret = 'Password1'                                                   │
│      user = 'postgres'                                                    │
│  username = 'postgres'                                                    │
╰───────────────────────────────────────────────────────────────────────────╯
```

```
0.2.0
╭───────────────────────────── <class 'dsnparse.ParseResult'> ─────────────────────────────╮
│ hold the results of a parsed dsn                                                         │
│                                                                                          │
│ ╭──────────────────────────────────────────────────────────────────────────────────────╮ │
│ │ <dsnparse.ParseResult object at 0x106081e20>                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                          │
│         anchor = ''                                                                      │
│       database = 'postgres'                                                              │
│         dbname = 'postgres'                                                              │
│         fields = {                                                                       │
│                      'scheme': 'postgresql',                                             │
│                      'username': 'postgres',                                             │
│                      'password': 'Password1',                                            │
│                      'hostname': 'localhost',                                            │
│                      'hosts': [('localhost', None)],                                     │
│                      'port': None,                                                       │
│                      'path': '/postgres',                                                │
│                      'params': '',                                                       │
│                      'query': 'test=123',                                                │
│                      'fragment': '',                                                     │
│                      'query_params': {'test': 123}                                       │
│                  }                                                                       │
│           host = 'localhost'                                                             │
│        hostloc = 'localhost'                                                             │
│         netloc = 'postgres:Password1@localhost'                                          │
│         parser = {                                                                       │
│                      'scheme': 'postgresql',                                             │
│                      'username': 'postgres',                                             │
│                      'password': 'Password1',                                            │
│                      'hosts': [('localhost', None)],                                     │
│                      'hostname': 'localhost',                                            │
│                      'port': None,                                                       │
│                      'path': '/postgres',                                                │
│                      'query': 'test=123',                                                │
│                      'query_params': {'test': 123},                                      │
│                      'fragment': ''                                                      │
│                  }                                                                       │
│ parser_classes = [<class 'dsnparse.ConnectionString'>, <class 'dsnparse.ConnectionURI'>] │
│          parts = ['postgres']                                                            │
│      pathparts = ['postgres']                                                            │
│          paths = ['postgres']                                                            │
│        schemes = ['postgresql']                                                          │
│         secret = 'Password1'                                                             │
│           user = 'postgres'                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────╯

```

**Comment by dlawin** [comment]
We will release a fix soon, but if you're stumbling across this issue in the meantime, the workaround is:
`pip install 'dsnparse==0.1.15'`


Thanks for discovering this and doing all of the debugging @dmorel !
