### ISSUE TITLE
Can't retry after connection closed

### ISSUE THREAD

**Issue by cacondie** [datafold/data-diff#648]
**Describe the bug**
I am comparing a Postgres database to a Databricks database using a python script. Our Postgres connection has a lot of safe guards to protect operational services. If data-diff is reading from a table and another process comes along that needs that table,  the system will just terminate the data-diff connection. And data-diff will come back with an error saying " terminating connection due to conflict with recovery"

I have attempted to solve this issue by wrapping my python script in a function using a retry decorator (which waits a handful of seconds and then tries again). However, it seems that the data-diff only gets a connection one time because all the retries will come back with the error: "ERROR - Error while comparing tables "xyz" and "xyz" : due to connection already closed"

Is there a way to allow data-diff to get a new connection after the first one gets closed?

Make sure to include the following (minus sensitive information):
- The command or code you used: I'm using data_diff.connect_to_table and data_diff.diff_tables functions in a python script
- The run output + error you're getting. (including tracestack):
- [2023-07-19, 17:30:26 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/usr/local/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/usr/local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/usr/local/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/airflow/utilities/data_diff_utility/data_diff.py", line 18, in diff_tables
    raise e
  File "/usr/local/airflow/utilities/data_diff_utility/data_diff.py", line 13, in diff_tables
    return list(dd.diff_tables(table1, table2))
  File "/usr/local/lib/python3.10/site-packages/data_diff/diff_tables.py", line 95, in __iter__
    for i in self.diff:
  File "/usr/local/lib/python3.10/site-packages/data_diff/diff_tables.py", line 246, in _diff_tables_wrapper
    raise error
  File "/usr/local/lib/python3.10/site-packages/data_diff/diff_tables.py", line 216, in _diff_tables_wrapper
    table1, table2 = self._threaded_call("with_schema", [table1, table2])
  File "/usr/local/lib/python3.10/site-packages/data_diff/diff_tables.py", line 51, in _threaded_call
    return list(self._thread_map(methodcaller(func), iterable))
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/data_diff/table_segment.py", line 149, in with_schema
    return self._with_raw_schema(self.database.query_table_schema(self.table_path))
  File "/usr/local/lib/python3.10/site-packages/data_diff/sqeleton/databases/base.py", line 414, in query_table_schema
    rows = self.query(self.select_table_schema(path), list)
  File "/usr/local/lib/python3.10/site-packages/data_diff/sqeleton/databases/base.py", line 368, in query
    res = self._query(sql_code)
  File "/usr/local/lib/python3.10/site-packages/data_diff/sqeleton/databases/base.py", line 572, in _query
    return r.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/data_diff/sqeleton/databases/base.py", line 578, in _query_in_worker
    return self._query_conn(self.thread_local.conn, sql_code)
  File "/usr/local/lib/python3.10/site-packages/data_diff/sqeleton/databases/base.py", line 528, in _query_conn
    c = conn.cursor()
psycopg2.InterfaceError: connection already closed

**Describe the environment**
I've encountered this issue running data-diff locally (running window 10), as well as on Astronomer Airflow (our production environment) (which I believe is a Debian). The version of data-diff I'm currently running is 0.7.13

**Comment by dlawin** [comment]
I believe this is being caused by the `shared` bool here:
https://github.com/datafold/data-diff/blob/eb22d3e9a8b1a098f113c7a37dec9a8efb25c025/data_diff/sqeleton/databases/_connect.py#L259

That being True will cache the connection and the api method is using the default since it's not being set [here](https://github.com/datafold/data-diff/blob/eb22d3e9a8b1a098f113c7a37dec9a8efb25c025/data_diff/__init__.py#L35)


I see two options:
- add a shared bool to the [connect_to_table](https://github.com/datafold/data-diff/blob/eb22d3e9a8b1a098f113c7a37dec9a8efb25c025/data_diff/__init__.py#L14) api method
- or you could implement a custom `connect_to_table` method in your script that sets `db = connect(db_info, thread_count=thread_count, shared=False)`
