### ISSUE TITLE
data-diff does NOT work with dbt version 1.6.0

### ISSUE THREAD

**Issue by sungchun12** [datafold/data-diff#660]
**Describe the bug**

I updated dbt to version 1.6.0 with the snowflake adapter, but it keeps showing this error. The `manifest.json` probably has changed.

Looks like the manifest upgraded to v10 from v9: https://schemas.getdbt.com/dbt/manifest/v10.json

![image](https://github.com/datafold/data-diff/assets/19176976/fb4b2753-3cd8-4626-b32d-93de79c1858c)
![image](https://github.com/datafold/data-diff/assets/19176976/6a136e67-a3e4-447f-92c2-97a4134ce5de)

Make sure to include the following (minus sensitive information):
- The command or code you used
- The run output + error you're getting. (including tracestack)
- Run data-diff with the `-d` switch for extra debug information.

If possible, please paste these as text, and not a screenshot.

```shell
 ~/Desktop/datafold-demo-sung  test-pr *1 !4  data-diff --dbt -d                                                                                     1 ✘  6s  datafold-demo-sung 🐍  02:26:18 PM 
Running with data-diff=0.8.0
14:27:04 INFO     Parsing file dbt_project.yml                                                                                                                                         dbt_parser.py:247
         INFO     Parsing file /Users/sung/Desktop/datafold-demo-sung/target/manifest.json                                                                                             dbt_parser.py:240
         ERROR    Not a soft of manifest.json                                                                                                                                            __main__.py:327
Traceback (most recent call last):
  File "/Users/sung/Desktop/datafold-demo-sung/venv/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/data_diff/__main__.py", line 311, in main
    dbt_diff(
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/data_diff/dbt.py", line 79, in dbt_diff
    dbt_parser = DbtParser(profiles_dir_override, project_dir_override, state)
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/data_diff/dbt_parser.py", line 109, in __init__
    self.dev_manifest_obj = self.get_manifest_obj(self.project_dir / MANIFEST_PATH)
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/data_diff/dbt_parser.py", line 242, in get_manifest_obj
    manifest_obj = parse_manifest(manifest=manifest_dict)
  File "/Users/sung/Desktop/datafold-demo-sung/venv/lib/python3.9/site-packages/dbt_artifacts_parser/parser.py", line 100, in parse_manifest
    raise ValueError("Not a soft of manifest.json")
ValueError: Not a soft of manifest.json
```

**Describe the environment**

Describe which OS you're using, which data-diff version, and any other information that might be relevant to this bug.

Used this public demo repo: https://github.com/datafold/datafold-demo-sung/tree/test-pr

data-diff version: 0.8.0
dbt version: 1.6.0
dbt-snowflake version: 1.6.0
MacOS
Python Version: 3.9.6

**Comment by sungchun12** [comment]
Looks like we need to bring in the latest version of the dbt-artifacts-parser to fix this: https://github.com/yu-iskw/dbt-artifacts-parser/blob/main/dbt_artifacts_parser/parser.py#L73C60-L73C71

**Comment by sungchun12** [comment]
It may be as simple as importing the latest version of the above package: https://github.com/yu-iskw/dbt-artifacts-parser/releases/tag/v0.3.2
