### ISSUE TITLE
data-diff fails when dbt anonymous usage is disabled

### ISSUE THREAD

**Issue by eschrock** [datafold/data-diff#750]
**Describe the bug**

Running `data-diff` fails:

```
Running with data-diff=0.9.7
04:09:46 ERROR    1 validation error for ManifestJsonConfig                                                                                                                     __main__.py:332
                  metadata -> user_id                                                                                                                                                          
                    none is not an allowed value (type=type_error.none.not_allowed)                                                                                                            
Traceback (most recent call last):
  File "/usr/local/bin/data-diff", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/data_diff/__main__.py", line 315, in main
    dbt_diff(
  File "/usr/local/lib/python3.10/site-packages/data_diff/dbt.py", line 83, in dbt_diff
    dbt_parser = DbtParser(profiles_dir_override, project_dir_override, state)
  File "/usr/local/lib/python3.10/site-packages/data_diff/dbt_parser.py", line 128, in __init__
    self.dev_manifest_obj = self.get_manifest_obj(self.project_dir / MANIFEST_PATH)
  File "/usr/local/lib/python3.10/site-packages/data_diff/dbt_parser.py", line 282, in get_manifest_obj
    manifest_obj = ManifestJsonConfig.parse_obj(manifest_dict)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ManifestJsonConfig
metadata -> user_id
  none is not an allowed value (type=type_error.none.not_allowed)
```

Sure enough, looking at the pydantic model in data-diff the field is not declared optional:

```
class ManifestJsonConfig(BaseModel):
    class Metadata(BaseModel):
        dbt_version: str = Field(..., regex=r"^\d+\.\d+\.\d+([a-zA-Z0-9]+)?$")
        project_id: str
        user_id: str
```

While the [manifest schema](https://schemas.getdbt.com/dbt/manifest/v10.json) clearly states that it is optional:

```
        "user_id": {
          "oneOf": [
            {
              "type": "string",
              "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
            },
            {
              "type": "null"
            }
          ],
          "description": "A unique identifier for the user"
        },
```

**Describe the environment**

I believe this is caused by this config in the dbt profile for the project:

```
config:
    send_anonymous_usage_stats: False
```

**Comment by dlawin** [comment]
Good catch @eschrock ! Are you open to submitting a PR?

**Comment by eschrock** [comment]
Yep I can do that. If there are any tests for this type of thing I may need some guidance, but happy to take a shot

**Comment by dlawin** [comment]
same problem likely exists with 
```
class ManifestJsonConfig(BaseModel):
    class Metadata(BaseModel):
      project_id: str 
```
      
That's another anonymous usage id from dbt

**Comment by sungchun12** [comment]
merged this fix: https://github.com/datafold/data-diff/pull/769
