### ISSUE TITLE
PydanticUserError('`regex` is removed. use `pattern` instead', code='removed-kwargs')

### ISSUE THREAD

**Issue by whitney** [datafold/data-diff#872]
## Bug description:
When I run `data-diff` I get an exception about the usage of regex in Pydantic Fields:
```
Traceback (most recent call last):
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/bin/data-diff", line 5, in <module>
    from data_diff.__main__ import main
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/__main__.py", line 18, in <module>
    from data_diff.dbt import dbt_diff
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/dbt.py", line 22, in <module>
    from data_diff.cloud import DatafoldAPI, TCloudApiDataDiff, TCloudApiOrgMeta
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/cloud/__init__.py", line 2, in <module>
    from data_diff.cloud.data_source import get_or_create_data_source
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/cloud/data_source.py", line 18, in <module>
    from data_diff.dbt_parser import DbtParser
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/dbt_parser.py", line 13, in <module>
    from data_diff.dbt_config_validators import ManifestJsonConfig, RunResultsJsonConfig
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/dbt_config_validators.py", line 6, in <module>
    class ManifestJsonConfig(BaseModel):
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/dbt_config_validators.py", line 7, in ManifestJsonConfig
    class Metadata(BaseModel):
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/data_diff/dbt_config_validators.py", line 8, in Metadata
    dbt_version: str = Field(..., regex=r"^\d+\.\d+\.\d+([a-zA-Z0-9]+)?$")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages/pydantic/fields.py", line 751, in Field
    raise PydanticUserError('`regex` is removed. use `pattern` instead', code='removed-kwargs')
pydantic.errors.PydanticUserError: `regex` is removed. use `pattern` instead
```

## Command run:
```
data-diff \
  --conf ./datadiff.toml \
  --run postgres_vs_snowflake \
  --algorithm hashdiff \
  --json > datadiff_report.json
```
### Contents of datadiff.toml:
```toml
[database.postgres_connection]
  driver = "postgresql"
  database = "<PG_DATABASE>"
  user = "<PG_USERNAME>"
  password = "<PASSWORD_STRING>"

[database.snowflake_connection]
  driver "snowflake"
  database = "XXX"
  user = "XXX"
  password = "XXX"
  account = "XXX"
  schema = "PUBLIC"
  warehouse = "XXX"
  role = "XXX"


[run.default]
  verbose = true

[run.postgres_vs_snowflake]
  # Source 1 ("left")
  1.database = "postgresql://<username>:<pwd>@<host>/<db>?options=-c%20statement_timeout%3D0"
  1.table = "xxx"

  # Source 2 ("right")
  2.database = "snowflake_connection"
  2.table = "XXX"

  verbose = false
```

If possible, please paste these as text, and not a screenshot.

**Describe the environment**
- OS: Mac OSX 13.6
- datadiff version: 0.11.1
- Pydantic version: 2.6.3
- all deps:
```
pip install data-diff 'data-diff[postgresql,snowflake]' -U                                                                                         (dbfuzz312) 12:11:08
Requirement already satisfied: data-diff in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (0.11.1)
Requirement already satisfied: attrs>=23.1.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (23.2.0)
Requirement already satisfied: click>=8.1 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (8.1.7)
Requirement already satisfied: dbt-core<2.0.0,>=1.0.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (1.7.8)
Requirement already satisfied: dsnparse<0.2.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (0.1.15)
Requirement already satisfied: keyring in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (24.3.1)
Requirement already satisfied: mashumaro<3.11.0,>=2.9 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from mashumaro[msgpack]<3.11.0,>=2.9->data-diff) (3.10)
Requirement already satisfied: pydantic>=1.10.12 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (2.6.3)
Requirement already satisfied: rich in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (13.7.0)
Requirement already satisfied: tabulate>=0.9.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (0.9.0)
Requirement already satisfied: toml>=0.10.2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (0.10.2)
Requirement already satisfied: typing-extensions>=4.0.1 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (4.9.0)
Requirement already satisfied: urllib3<2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff) (1.26.18)
Requirement already satisfied: cryptography in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff[postgresql,snowflake]) (42.0.4)
Requirement already satisfied: psycopg2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff[postgresql,snowflake]) (2.9.9)
Requirement already satisfied: snowflake-connector-python<4.0.0,>=3.0.2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from data-diff[postgresql,snowflake]) (3.7.1)
Requirement already satisfied: agate~=1.7.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (1.7.1)
Requirement already satisfied: Jinja2~=3.1.2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (3.1.3)
Requirement already satisfied: logbook<1.6,>=1.5 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (1.5.3)
Requirement already satisfied: networkx<4,>=2.3 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (3.2.1)
Requirement already satisfied: colorama<0.5,>=0.3.9 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (0.4.6)
Requirement already satisfied: pathspec<0.12,>=0.9 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (0.11.2)
Requirement already satisfied: isodate<0.7,>=0.6 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (0.6.1)
Requirement already satisfied: sqlparse<0.5,>=0.2.3 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (0.4.4)
Requirement already satisfied: dbt-extractor~=0.5.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (0.5.1)
Requirement already satisfied: minimal-snowplow-tracker~=0.0.2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (0.0.2)
Requirement already satisfied: dbt-semantic-interfaces~=0.4.2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (0.4.4)
Requirement already satisfied: jsonschema>=3.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (4.21.1)
Requirement already satisfied: packaging>20.9 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (23.2)
Requirement already satisfied: protobuf>=4.0.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (4.25.3)
Requirement already satisfied: pytz>=2015.7 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (2024.1)
Requirement already satisfied: pyyaml>=6.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (6.0.1)
Requirement already satisfied: cffi<2.0.0,>=1.9 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (3.6)
Requirement already satisfied: requests<3.0.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-core<2.0.0,>=1.0.0->data-diff) (2.31.0)
Requirement already satisfied: msgpack>=0.5.6 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from mashumaro[msgpack]<3.11.0,>=2.9->data-diff) (1.0.7)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from pydantic>=1.10.12->data-diff) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from pydantic>=1.10.12->data-diff) (2.16.3)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (1.5.1)
Requirement already satisfied: pyOpenSSL<25.0.0,>=16.2.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (24.0.0)
Requirement already satisfied: pyjwt<3.0.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (2.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (2024.2.2)
Requirement already satisfied: filelock<4,>=3.5 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (3.13.1)
Requirement already satisfied: sortedcontainers>=2.4.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (2.4.0)
Requirement already satisfied: platformdirs<4.0.0,>=2.6.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (3.11.0)
Requirement already satisfied: tomlkit in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from snowflake-connector-python<4.0.0,>=3.0.2->data-diff[postgresql,snowflake]) (0.12.3)
Requirement already satisfied: jaraco.classes in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from keyring->data-diff) (3.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from rich->data-diff) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from rich->data-diff) (2.17.2)
Requirement already satisfied: Babel>=2.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core<2.0.0,>=1.0.0->data-diff) (2.14.0)
Requirement already satisfied: leather>=0.3.2 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core<2.0.0,>=1.0.0->data-diff) (0.4.0)
Requirement already satisfied: parsedatetime!=2.5,>=2.1 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core<2.0.0,>=1.0.0->data-diff) (2.6)
Requirement already satisfied: python-slugify>=1.2.1 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core<2.0.0,>=1.0.0->data-diff) (8.0.4)
Requirement already satisfied: pytimeparse>=1.1.5 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core<2.0.0,>=1.0.0->data-diff) (1.1.8)
Requirement already satisfied: pycparser in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from cffi<2.0.0,>=1.9->dbt-core<2.0.0,>=1.0.0->data-diff) (2.21)
Requirement already satisfied: importlib-metadata~=6.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-semantic-interfaces~=0.4.2->dbt-core<2.0.0,>=1.0.0->data-diff) (6.11.0)
Requirement already satisfied: more-itertools<11.0,>=8.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-semantic-interfaces~=0.4.2->dbt-core<2.0.0,>=1.0.0->data-diff) (10.2.0)
Requirement already satisfied: python-dateutil~=2.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from dbt-semantic-interfaces~=0.4.2->dbt-core<2.0.0,>=1.0.0->data-diff) (2.8.2)
Requirement already satisfied: six in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from isodate<0.7,>=0.6->dbt-core<2.0.0,>=1.0.0->data-diff) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from Jinja2~=3.1.2->dbt-core<2.0.0,>=1.0.0->data-diff) (2.1.5)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from jsonschema>=3.0->dbt-core<2.0.0,>=1.0.0->data-diff) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from jsonschema>=3.0->dbt-core<2.0.0,>=1.0.0->data-diff) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from jsonschema>=3.0->dbt-core<2.0.0,>=1.0.0->data-diff) (0.18.0)
Requirement already satisfied: mdurl~=0.1 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->data-diff) (0.1.2)
Requirement already satisfied: zipp>=0.5 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from importlib-metadata~=6.0->dbt-semantic-interfaces~=0.4.2->dbt-core<2.0.0,>=1.0.0->data-diff) (3.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /Users/wzoller/miniconda3/envs/dbfuzz312/lib/python3.12/site-packages (from python-slugify>=1.2.1->agate~=1.7.0->dbt-core<2.0.0,>=1.0.0->data-diff) (1.3)
```

**Comment by whitney** [comment]
Downgrading my Pydantic install to 1.10.12 resolves the issue.
